// src/client/Taskbar.tsx
import { useState } from 'react';
import Icon from '../components/Icon';
import Clock from '../components/Clock';
import { removeByIndex, updateByIndex } from '../util/array';
import { Start } from './Start';

import classNames from 'classnames';
import { addInstance } from '../redux/instances';
import { useDispatch } from '../redux';

import './Taskbar.css';

type AppPreview = {
    name: string;
    hiding: boolean;
};

export function Taskbar() {
    const apps = [
        'opera',
        'settings',
        'dfyd',
        'para-el',
        'vsc'
    ];

    const [previewingApps, setPreviewingApps] = useState<AppPreview[]>([]);

    const onPreview = (appName: string) => {
        setPreviewingApps(apps => [...apps, { name: appName, hiding: false }]);
    };
    const onHide = (appName: string) => {
        setPreviewingApps(apps => {
            return updateByIndex(apps, app => app.name === appName, app => ({ ...app, hiding: true }));
        });
    };
    const onRemove = (appName: string) => {
        setPreviewingApps(apps => {
            return removeByIndex(apps, app => app.name === appName);
        });
    };

    return (
        <div className="taskbar">
            <div className="start">
                <Start />
            </div>
            <div className="container">
                <div className="left">
                    <div className="search">
                        <Icon>search</Icon>
                    </div>
                    <div className="app-tray">
                        {apps.map(app => <App key={app} name={app} />)}
                    </div>
                </div>
                <div className="right">
                    <div className="secondary-controls"></div>
                    <div className="lang-switch"></div>
                    <Clock />
                    <div className="show-desktop"></div>
                </div>
            </div>
            <div className="context" />
            <div className="previews">
                <div className="previews-control previews-up disabled"></div>
                <div className="previews-list"></div>
                <div className="previews-control previews-down"></div>
            </div>
            <div class="preview">
            </div>
        </div>
    );
}

type AppProps = {
    name: string;
};

export function App({ name }: AppProps) {
    const [ hovered, setHovered ] = useState(false);
    const dispatch = useDispatch();

    const onMouseEnter = () => {
        setHovered(true);
    }
    const onMouseLeave = () => {
        setHovered(false);
    };
    const onClick = () => {
        dispatch(
            addInstance({
                appId: name
            })
        );
    };

    return (
        <div
            class={classNames('app', hovered && 'hover')}
            data-name={name}
            onMouseEnter={onMouseEnter}
            onMouseLeave={onMouseLeave}
            onClick={onClick}
        >
            <div className="icon">
                <div className={name}>
                    <Icon>api</Icon>
                </div>
            </div>
            <div className="panels">
            </div>
        </div>
    )
}

function Panel() {
    return (
        <div class="panel">
            <div class="indicator" />
        </div>
    );
}

// src/lib/client/Taskbar.svelte
<script lang="ts">
    import { Icon } from '$lib/components';
</script>

<div class="taskbar">
    <div class="start">
        <!-- <Start /> -->
    </div>
    <div class="container">
        <div class="left">
            <div class="search">
                <Icon name="search" />
            </div>
            <div class="app-tray">
                <!-- {apps.map(app => <App key={app} name={app} />)} -->
            </div>
        </div>
        <div class="right">
            <div class="secondary-controls" />
            <div class="lang-switch" />
            <!-- <Clock /> -->
            <div class="show-desktop" />
        </div>
    </div>
    <div class="context" />
    <div class="previews">
        <div class="previews-control previews-up disabled" />
        <div class="previews-list" />
        <div class="previews-control previews-down" />
    </div>
    <div class="preview" />
</div>

<style lang="scss">
    .taskbar {
        @include flex;
        height: 44px;
        font-size: 12px;

        .container {
            @include flex(centerY, between);
            background-color: var(--taskbar);
            backdrop-filter: blur(5px);
        }

        .left,
        .right {
            @include flex;
        }

        .search {
            @include flex(center);
            width: 58px;
            background-color: transparent;
            margin-right: 1px;
            transition: 0.3s background-color;

            &:hover {
                background-color: hsla(
                    var(--color-hue, 180),
                    var(--color-sat, 100%),
                    var(--color-lig, 50%),
                    0.1
                );
            }
        }

        .app-tray {
            @include flex;

            .app {
                @include flex(centerX);
                width: 58px;
                margin-right: 1px;
                transition:
                    0.3s margin-left,
                    0.3s opacity;

                &.hover .panels:empty,
                &.hover .panels .panel {
                    background-color: hsla(
                        var(--color-hue, 180),
                        var(--color-sat, 100%),
                        var(--color-lig, 50%),
                        0.1
                    );
                }

                &:active .panels:empty,
                &:active .panels .panel {
                    background-color: hsla(
                        var(--color-hue, 180),
                        var(--color-sat, 100%),
                        var(--color-lig, 50%),
                        0.12
                    );
                }

                &.active .panels .panel {
                    background-color: hsla(
                        var(--color-hue, 180),
                        var(--color-sat, 100%),
                        var(--color-lig, 50%),
                        0.15
                    );
                }

                &.active:hover .panels .panel {
                    background-color: hsla(
                        var(--color-hue, 180),
                        var(--color-sat, 100%),
                        var(--color-lig, 50%),
                        0.2
                    );
                }

                &.active:active .panels .panel {
                    background-color: hsla(
                        var(--color-hue, 180),
                        var(--color-sat, 100%),
                        var(--color-lig, 50%),
                        0.25
                    );
                }

                &:hover .panels .panel:first-of-type:only-child,
                &.active .panels .panel:first-of-type:only-child {
                    width: 58px;
                }

                &.app:hover .panels .panel:first-of-type:nth-last-of-type(2),
                &.app.active .panels .panel:first-of-type:nth-last-of-type(2) {
                    width: 54px;
                }

                &.app:hover .panels .panel:first-of-type,
                &.app.active .panels .panel:first-of-type {
                    width: 50px;
                }

                &.app:hover .panels .panel:nth-of-type(2),
                &.app.active .panels .panel:nth-of-type(2),
                &.app:hover .panels .panel:nth-of-type(3),
                &.app.active .panels .panel:nth-of-type(3) {
                    width: 4px;
                }

                .label {
                    @include flex(center);
                }

                .icon {
                    @include flex(center);
                    height: 100%;
                    width: 100%;
                    position: absolute;
                    user-select: none;
                    z-index: 1;

                    .tooltip {
                        transform: translate(-50%, calc(-100% - 18px));
                    }
                }

                .panels {
                    @include flex;
                    // height: 100%;
                    transition: 0.3s background-color;

                    .panel {
                        @include flex(endY);
                        // height: 100%;
                        transition: 0.3s;
                        /* animation: fadeIn .5s forwards; */

                        &.hidden {
                            filter: opacity(0);
                        }

                        /** Single panel **/
                        &:first-of-type:only-child {
                            width: 52px;
                        }

                        /** Double panel **/
                        &:first-of-type:nth-last-of-type(2) {
                            width: 42px;
                        }

                        /** Triple panel **/
                        &:first-of-type {
                            width: 32px;
                        }

                        &:nth-of-type(2),
                        &:nth-of-type(3) {
                            width: 10px;
                        }

                        &:nth-of-type(2) {
                            filter: brightness(0.7);
                        }

                        &:nth-of-type(3) {
                            filter: brightness(0.5);
                        }

                        .indicator {
                            @include flex;
                            background-color: rgb(var(--color-rgb));
                            width: 100%;
                            height: 3px;
                        }
                    }
                }
            }
        }
    }
</style>
